### ISSUE TITLE
insert data is not success

### ISSUE THREAD

**Issue by it2911** [zilliztech/MolSearch#13]
When I run `python3 insert_data.py -f test_1w.smi `, the error below is shown.  Please confirm which step was wrong. Thank you.
```
-----len of vectors: 10000
connect the database!
CREATE TABLE molsearch (smiles text, ids bigint);
can't create postgres table
copy molsearch from '/home/cheng/MolSearch/script/test_1w.smi'; create index mols_ids on molsearch(ids);
Traceback (most recent call last):
  File "insert_data.py", line 57, in copy_data_to_pg
    cur.execute(sql1)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insert_data.py", line 157, in <module>
    main(sys.argv[1:])
  File "insert_data.py", line 151, in main
    do_load(file_path)
  File "insert_data.py", line 131, in do_load
    copy_data_to_pg(conn, cur, file_path)
  File "insert_data.py", line 61, in copy_data_to_pg
    print(oe.message)
AttributeError: 'InFailedSqlTransaction' object has no attribute 'message'

```

**Comment by shiyu22** [comment]
It seems like a PostgreSQL issue, you can follow [this answer](https://stackoverflow.com/questions/2979369/databaseerror-current-transaction-is-aborted-commands-ignored-until-end-of-tra).

BTW, #14, this repo will no longer be maintained, please visit https://github.com/milvus-io/bootcamp/tree/master/solutions/molecular_similarity_search.
